name: GriefHeal
version: 1.3
main: com.webbservermc.griefheal.GriefHeal
api-version: 1.21
description: World restoration with SQLite, spatial debouncing, and priority sorting.
authors: [adamwbb]

commands:
  griefheal:
    description: Main command for GriefHeal.
    aliases: [gh]
    permission: griefheal.admin
    usage: /<command> [reload|now]

permissions:
  griefheal.admin:
    description: Allows access to reload and force heal commands.
    default: op